function [methodinfo,structs,enuminfo,ThunkLibName]=mLogistic
%MLOGISTIC Create structures to define interfaces found in 'Logistic'.

%This function was generated by loadlibrary.m parser version  on Sun Jun 28 12:08:51 2015
%perl options:'Logistic.i -outfile=mLogistic.m -thunkfile=Logistic_thunk_pcwin64.c -header=Logistic.h'
ival={cell(1,0)}; % change 0 to the actual number of functions to preallocate the data.
structs=[];enuminfo=[];fcnNum=1;
fcns=struct('name',ival,'calltype',ival,'LHS',ival,'RHS',ival,'alias',ival,'thunkname', ival);
MfilePath=fileparts(mfilename('fullpath'));
ThunkLibName=fullfile(MfilePath,'Logistic_thunk_pcwin64');
% void logistical ( float *, float *, float *, int *, double *); 
fcns.thunkname{fcnNum}='voidvoidPtrvoidPtrvoidPtrvoidPtrvoidPtrThunk';fcns.name{fcnNum}='logistical'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}=[]; fcns.RHS{fcnNum}={'singlePtr', 'singlePtr', 'singlePtr', 'int32Ptr', 'doublePtr'};fcnNum=fcnNum+1;
methodinfo=fcns;