function [methodinfo,structs,enuminfo,ThunkLibName]=mPoly
%MPOLY Create structures to define interfaces found in 'Poly'.

%This function was generated by loadlibrary.m parser version  on Sun Jun 28 15:26:03 2015
%perl options:'Poly.i -outfile=mPoly.m -thunkfile=Poly_thunk_pcwin64.c -header=Poly.h'
ival={cell(1,0)}; % change 0 to the actual number of functions to preallocate the data.
structs=[];enuminfo=[];fcnNum=1;
fcns=struct('name',ival,'calltype',ival,'LHS',ival,'RHS',ival,'alias',ival,'thunkname', ival);
MfilePath=fileparts(mfilename('fullpath'));
ThunkLibName=fullfile(MfilePath,'Poly_thunk_pcwin64');
% void polynomial ( int *, float *, int *, int *, float *, float *, double *); 
fcns.thunkname{fcnNum}='voidvoidPtrvoidPtrvoidPtrvoidPtrvoidPtrvoidPtrvoidPtrThunk';fcns.name{fcnNum}='polynomial'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}=[]; fcns.RHS{fcnNum}={'int32Ptr', 'singlePtr', 'int32Ptr', 'int32Ptr', 'singlePtr', 'singlePtr', 'doublePtr'};fcnNum=fcnNum+1;
methodinfo=fcns;